version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: docker build
          command: docker build -t qmk_firmware .
      - run:
          name: docker run
          command: docker run -e keyboard=ergodox_ez -e keymap=default --rm -v $('pwd'):/qmk:rw -t qmk_firmware
      - store_artifacts:
          path: ergodox_ez_default.hex