version: 2
jobs:
  build:
    machine: true
    environment:
        CIRCLE_ARTIFACTS: /tmp/artifacts
    steps:
      - checkout
      - run: mkdir -p $CIRCLE_ARTIFACTS
      - run:
          name: docker build
          command: docker build -t qmk_firmware .
      - run:
          name: docker run
          command: docker run -e keyboard=ergodox_ez -e keymap=default --rm -v $('pwd'):/qmk:rw -t qmk_firmware
      - store_artifacts:
          path: .build
      - store_artifacts:
          path: qmk_firmware/.build
      - run: ls .build